Healthnet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('home.urls')),
    #url(r'^home/',include('home.urls')),
    url(r'^',include('home.urls',namespace="home")),
    url(r'^home/',include('home.urls',namespace="home")),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name='home'
urlpatterns = [
    # ex: /home/
    url(r'^$', views.index, name='index'),
    # ex: /home/patient/
    url(r'^patient/$', views.PatientView.as_view(), name='patient'),
    # ex: /home/administrator
    url(r'^administrator/$', views.AdministratorView.as_view(), name='administrator'),
    # ex: /home/doctor/
    url(r'doctor/$', views.DoctorView.as_view(), name='doctor'),
    # ex: /home/nurse
    url(r'^nurse/$',views.NurseView.as_view(), name='nurse'),
    # ex: home/patient/1
    url(r'^patient/(?P<patient_id>[0-9]+)/$', views.pDetail, name='pDetail'),
    # ex: home/doctor/1
    url(r'^doctor/(?P<doctor_id>[0-9]+)/$', views.dDetail, name='dDetail'),
    url(r'^nurse/(?P<nurse_id>[0-9]+)/$', views.nDetail, name='nDetail'),
    # ex: home/register/
    url(r'register/', views.RegistrationForm.as_view(), name='register'),
    # ex: home/activities/
    url(r'activities/', views.ActivityView.as_view(), name='activities'),
    # ex: /polls/5/contact
    url(r'^(?P<patient_id>[0-9]+)/contact/$',views.ContactEditForm.as_view(), name='contact'),
    url(r'^(?P<patient_id>[0-9]+)/medical/$',views.MedicalEditForm.as_view(), name='medical'),
    url(r'login/$', views.LoginView.as_view(),name='login'),
    url(r'logout/$', views.LogOutView.as_view(),name='logout'),
    url(r'appointment/$', views.newAppointment.as_view(), name='appointment')
]

home/models/activity.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import sqlite3

"""
This class represents activity objects. It stores information based on actions in other class methods.
:atrb: timestamp: Time when activity was done.
:atrb: User_ID: Identification of the user that performed the activity.
:atrb: Effected_ID: Identification of the user affected by the activity (can be same as User_ID)
:atrb: Activity_Details: Description of the action performed.
"""
class Activity(models.Model):
    timestamp = models.DateTimeField(default=timezone.now())
    User_ID = models.CharField(max_length=100, default='')
    Effected_ID = models.CharField(max_length=100, default='')
    Activity_Details = models.TextField(default="")
    def getActivity(self):
        return self.Activity_Details
    def getTime(self):
        return self.timestamp
    #Used to sort the database in time order such that the user can view the activity log by most recent date.
    def sortTable(self):
        sqlite_file = 'db.sqlite3'
        table_name = 'home_activity'
        conn = sqlite3.connect(sqlite_file)
        c = conn.cursor()
        c.execute('SELECT * FROM {home_activity} ORDER BY -{timestamp}')
    #creates a new activity object for other methods to use
    def createActivity(time, details,User_ID,user):
        activity = Activity (
            Effected_ID = User_ID,
            User_ID = user,
            timestamp = time,
            Activity_Details = details,        )
        activity.save()
    #creates a toString
    def __str__(self):
        return "Time: "+str(self.timestamp)+" | Details: "+str(self.Activity_Details)

home/models/activitylog.py
from django.db import models
from django.utils import timezone
from .activity import Activity

class ActivityLog(models.Model):
	activities = Activity.objects.all()

	def displayLog(self):
		pass

	#return log
	def addActivity(self):
		#log.append(self)
		pass

	def resetLog(self):
		time = models.DateTimeField()
		return time

	def __str__(self):
		return self.activities

home/models/administrator.py
from django.db import models
from django.contrib.auth.models import User
class Administrator(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return self.user.username

home/models/calendar.py
from django.db import models
from datetime import datetime
class Appointment(models.Model):
    dateTime = models.DateTimeField(blank= False, default=datetime.now)           #appointment date and time
    office = models.IntegerField('Room number:')    #office number of the doctor
    patient_ID = models.CharField(max_length=20, default='')    #patient user ID
    doctor_ID = models.CharField(max_length=20, default='')     #doctor user ID
    description = models.CharField(max_length=100, default='')  #description for the appointment

    def editTime(dateTime):
        pass

    def editDescription(description):
        pass

    def editLocation(office):
        pass

    def editPatient(patient_ID):
        pass

    def editDoctor(doctor_ID):
        pass

    def createAppoinment(appointment_form):
        appointment = Appointment(
            dateTime=appointment_form['dateTime'],
            office=appointment_form['office'],
            patient_ID=appointment_form['patient_ID'],
            doctor_ID=appointment_form['doctor_ID'],
            description=appointment_form['description']
        )
        appointment.save()
        return appointment

    def __str__(self):
        tostr = ""
        tostr += self.dateTime + " at office No." + self.office + "\n"
        tostr += " Patient ID: " + self.patient_ID + "\n Doctor ID: " + self.doctor_ID + "\n"
        tostr += "  Description: " + self.description
        return tostr

class Calendar(models.Model):
    Appointments = Appointment.objects.all
    User_ID = models.CharField(max_length=20, default='')


    def cancelAppointment(dateTime):
        pass

    def editAppointment(editState):
        pass

    def __str__(self):
        return self.User_ID

home/models/hospital.py
from django.db import models
from .doctor import Doctor
from .patient import Patient
from .nurse import Nurse

class Hospital(models.Model):
    # attributes
    hospital_ID = models.CharField(max_length=20, default='')
    doctors = Doctor.objects.all()
    patients = Patient.objects.all()
    nurses = Nurse.objects.all()

    #Methods
    def admitPatient(patient_ID):
        pass

    def dischargerPatient(paitent_ID):
        pass

    def transferPatient(patient_ID, hospital_ID):
        pass

home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields =['username','password','password_confirm','email','first_name','last_name']

class PatientUserForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['DOB',]

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['dateTime', 'office', 'patient_ID', 'doctor_ID', 'description']


class ContactUserForm(forms.ModelForm):
    phone = forms.RegexField(regex=r'^\+?1?\d{10}$')
    zip = forms.RegexField(regex= r'^\+?1?\d{5}')
    class Meta:
        model = ContactInfo
        fields = ['address','city','state','zip','phone']

class MedicalUserForm(forms.ModelForm):
    weight = forms.RegexField(regex=r'^\+?1?\d{1,3}')
    height = forms.RegexField(regex=r'^\+?1?\d{2,3}')
    class Meta:
        model = MedicalInfo
        fields = ['sex','weight','height','blood_Type']

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password']

home/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from django.views.generic import View
from datetime import datetime
from .models import *
from .forms import *

"""
This creates the index/homepage of Healthnet.
This is where initial navigation happens
"""
def index(request):
    return render(request, "home/index.html")

#======List Views=======================================================================================================
"""
A Class representing a generic list of all patients in the system
This List is of usernames, This may change in future
Accessible by anyone if logged in
"""
class PatientView(generic.ListView):
   template_name = 'home/patient/patient.html'
   context_object_name = "patient_list"
   """
   Gets the context_object. This is all patients
   """
   def get_queryset(self):
        return Patient.objects.all()
"""
A Class representing a generic list of all admin in the system
This List is of usernames, This may change in future
Accessible by anyone if logged in
"""
class AdministratorView(generic.ListView):
    template_name = 'home/administrator.html'
    context_object_name = "administrator_list"
    """
    This method gets and returns all administrators
    """
    def get_queryset(self):
        return User.objects.filter(is_superuser = True)
"""
A Class representing a generic list of all Doctors in the system
This List is of usernames, This may change in future
Accessible by anyone if logged in
"""
class DoctorView(generic.ListView):
    template_name = 'home/doctor.html'
    context_object_name = "doctor_list"
    """
    Gets and returns a list of all doctors
    """
    def get_queryset(self):
        return Doctor.objects.all()
"""
A Class representing a generic list of all Nurses in the system
This List is of usernames, This may change in future
Accessible by anyone if logged in
"""
class NurseView(generic.ListView):
    template_name = 'home/nurse.html'
    context_object_name = "nurse_list"
    """
    Gets and Returns all nurses
    """
    def get_queryset(self):
        return Nurse.objects.all()
"""
A Class representing a generic list of all Activities in the Activity Log
This List is of usernames, This may change in future
Accessible by anyone if logged in
"""
class ActivityView(generic.ListView):
    template_name = 'home/activities.html'
    context_object_name = "activity_list"
    """
    Returns the activity log
    """
    def get_queryset(self):
        today = datetime.now()
        return Activity.objects.filter(timestamp__year=today.year).order_by('-timestamp')
#======End List Views===================================================================================================

#======Detail Views=====================================================================================================
"""
This view is used when a user clicks on a patient's username
It gets all relevant User information and renders it using the context below
:arg
    patient_id: The id number of the patient, used to gather the information
:returns: a render of the user information page
"""
def pDetail(request,patient_id):
    patient = get_object_or_404(Patient, pk = patient_id)
    #gets the patient
    phone = patient.contact.phone
    phone = "%s%s%s-%s%s%s-%s%s%s%s" % tuple(phone) #formats phone
    weight = patient.medical.weight + " lb"
    doctors = Doctor.objects.all()
    doctorlist = []
    for doctor in doctors:
        doctorlist.append(doctor.user.username)
    nurses = Nurse.objects.all()
    for nurse in nurses:
        doctorlist.append(nurse.user.username)
    #these 4 lines are used to format the hieght
    if len(patient.medical.height) == 2:
        height = """ %s'%s" """ % tuple(patient.medical.height)
    else:
        height = """ %s'%s%s" """ % tuple(patient.medical.height)
    context = {
        'name': patient.name,
        'username': patient.username,
        'DOB': patient.DOB,
        'address': patient.contact.address,
        'city': patient.contact.city,
        'state': patient.contact.state,
        'zip': patient.contact.zip,
        'phone': phone,
        'email': patient.user.email,
        'patient': patient,
        'weight': weight,
        'height': height,
        'doctorlist': doctorlist
    }
    return render(request, "home/patient/patientDetail.html", context)

"""
This View is used to when a user clicks a Doctor's ID number
This displays all relevant class information
:arg
    doctor_id: the id number of the doctor
:returns: a render of the doctors info
"""
def dDetail(request,doctor_id):
    doctor = get_object_or_404(Doctor,pk = doctor_id)
    phone = doctor.phone
    phone = "%s%s%s-%s%s%s-%s%s%s%s" % tuple(phone)  # formats phone
    return render(request,"home/doctorDetail.html", {'doctor': doctor, 'phone': phone})

def nDetail(request,nurse_id):
    nurse = get_object_or_404(Nurse,pk = nurse_id)
    phone = nurse.phone
    phone = "%s%s%s-%s%s%s-%s%s%s%s" % tuple(phone)  # formats phone
    return render(request,"home/nDetail.html", {'nurse': nurse, 'phone': phone})
#======End Detail Views=================================================================================================

#======Registration and Update Views====================================================================================
class RegistrationForm(View):
    template_name='home/patient/register.html'
    # Displays signup form
    def get(self,request):
        user_form= UserForm
        patient_form = PatientUserForm
        contact_form = ContactUserForm
        medical_form = MedicalUserForm
        return render(request, self.template_name,{'user_form': user_form, 'patient_form': patient_form, 'contact_form':contact_form, 'medical_form': medical_form})
    #regesters a user
    def post(self,request):
        user_form = UserForm(request.POST)
        patient_form = PatientUserForm(request.POST)
        contact_form = ContactUserForm(request.POST)
        medical_form = MedicalUserForm(request.POST)
        if user_form.is_valid() and patient_form.is_valid() and contact_form.is_valid() and medical_form.is_valid():
            user_form_cleaned =  user_form.cleaned_data
            patient_form_cleaned = patient_form.cleaned_data
            contact_form_cleaned = contact_form.cleaned_data
            medical_form_cleaned  = medical_form.cleaned_data
            patient = Patient.createPatient(user_form_cleaned, patient_form_cleaned, contact_form_cleaned, medical_form_cleaned,request.user.username)
            patient.save()
            return redirect('home:login')
        else:
            return render(request, self.template_name, {'user_form': user_form, 'patient_form': patient_form, 'contact_form': contact_form, 'medical_form': medical_form})

class ContactEditForm(View):
    template_name = 'home/patient/contactU.html'

    def get(self, request,patient_id):
        #if request.user.is_authenticated:
            patient = get_object_or_404(Patient, pk=patient_id)
            contact_form = ContactUserForm(initial={
                "address": patient.contact.address, "city": patient.contact.city, "state": patient.contact.state,
                "zip": patient.contact.zip, 'phone': patient.contact.phone})

            return render(request, self.template_name,{'contact_form': contact_form, 'patient': patient})
       # else:
        #    return HttpResponse("Login to edit")

    def post(self,request,patient_id):
       # if request.user.is_authenticated:
            patient = get_object_or_404(Patient, pk=patient_id)
            contact_form = ContactUserForm(request.POST)
            if contact_form.is_valid():
                contact_form_clean = contact_form.cleaned_data
                patient = patient.UpdateContact(contact_form_clean,request.user.username)
                patient.save()
                return redirect('home:pDetail', patient_id)
            else:
                return render(request, self.template_name,
                              {'contact_form': contact_form, 'patient': patient})

class MedicalEditForm(View):
    template_name = 'home/patient/updateM.html'

    def get(self, request, patient_id):
        # if request.user.is_authenticated:
        doctors = Doctor.objects.all()
        doctorlist = []
        for doctor in doctors:
            doctorlist.append(doctor.user.username)
        nurses = Nurse.objects.all()
        for nurse in nurses:
            doctorlist.append(nurse.user.username)
        patient = get_object_or_404(Patient, pk=patient_id)
        medical_form = MedicalUserForm(initial={
            "sex": patient.medical.sex, "height": patient.medical.height, "weight": patient.medical.weight,
            "blood_Type": patient.medical.blood_Type})
        return render(request, self.template_name, {'medical_form': medical_form, 'patient': patient, 'doctorlist': doctorlist})
        # else:
        #    return HttpResponse("Login to edit")

    def post(self, request, patient_id):
        # if request.user.is_authenticated:
        patient = get_object_or_404(Patient, pk=patient_id)
        medical_form = MedicalUserForm(request.POST)
        if medical_form.is_valid():
            medical_form_clean = medical_form.cleaned_data
            patient = patient.UpdateMedical(medical_form_clean,request.user.username)
            patient.save()
            return redirect('home:pDetail', patient_id)
        else:
            return render(request, self.template_name,
                          {'contact_form': medical_form, 'patient': patient})


#======End Registration and Update Views================================================================================

home/templates/home/patient/contactU.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Contact</title>
    {% include "home/include/header.html" %}
</head>
<body>
{% if user.is_authenticated %}
    {% if user.username == patient.username %}
    <form method="POST">
        {% csrf_token %}
        {{ contact_form.as_p }}
        <button type="submit">Save changes</button>
    </form>
    {% else %}
        Only this patient can edit contact information
    {% endif %}
{% else %}
You must login or register to view this page<br/>
<button onclick="window.location. href='{% url 'home:register' %}'">
        Register New User Patient
</button><br/>
{% endif %}
<button onclick="window.location.href='/home/'">
    home
</button>
</body>
</html>

home/templates/home/patient/patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patients</title>

    {% include "home/include/header.html" %}
</head>
<body>

{% if user.is_authenticated %}
<h2>Patient List:</h2>
{% if patient_list %}
    <ul>
        {% for patient in patient_list %}
        <li><a href="{% url 'home:pDetail' patient.id %}">
            {{patient.user.username}}
        </a>
        </li>
        {% endfor %}
    </ul>
{%else%}
    <p> No Patients available</p>
{% endif %}
{% else %}
You must login or register to view this page<br/>
<button onclick="window.location. href='{% url 'home:register' %}'">
        Register New User Patient
</button><br/>
{% endif %}
<button onclick="window.location.href='/home'">
    return
</button>
</body>
</html>

home/templates/home/patient/patientDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{username}}</title>
    {% include "home/include/header.html" %}
</head>
<body>
{% if user.is_authenticated %}
<h2> Patient Name: {{ name }}<br/></h2>
Username: {{patient.user.username}}<br/>
Email: {{email}}<br/>
Sex: {{patient.medical.sex}}<br/>
DOB: {{DOB}}<br/>
Address: {{address}}, {{city}}, {{state}} {{zip}}<br/>
Phone: {{phone}}<br/>

    {% if user.username == patient.username or user.username in doctorlist%}
        Height: {{height}}<br/>
        Weight: {{weight}}<br/>
        Blood type: {{patient.medical.blood_Type}}<br/>
        {% if user.username != patient.username %}
            <a href="{% url 'home:medical' patient.id %}"> Edit Medical Information</a><br/>
        {% endif %}
    {% endif %}
    {% if user.username == patient.username %}
        <a href="{% url 'home:contact' patient.id %}"> Edit Contact Information</a><br/>
    {% endif %}
{%else%}
You must login or register to view this page<br/>
<button onclick="window.location. href='{% url 'home:register' %}'">
        Register New User Patient
</button><br/>
{% endif %}

<button onclick="window.location.href='/home/patient'">
    return
</button>
</body>
</html>

home/templates/home/patient/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    {% include "home/include/header.html" %}
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{user_form.as_p}}
    {{patient_form.as_p}}
    {{contact_form.as_p}}
    {{medical_form.as_p}}
    <button type="submit">Save changes</button>

</form>
    <button onclick="window.location.href='/home'">
    return
</button>

</body>
</html>

home/templates/home/patient/updateM.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Medical</title>
    {% include "home/include/header.html" %}
</head>
<body>

{% if user.is_authenticated  %}
    {% if user.username in doctorlist %}
        <form method="POST">
            {% csrf_token %}
            {{ medical_form.as_p }}
            <button type="submit">Save changes</button>
        </form>
    {%endif%}
    {%elif user.username = patient.username %}
        Only a doctor or nurse can edit medical information<br/>
        Please contact one:<br/>
        <a href="{% url 'home:doctor'%}">
            View Doctors</a><br/>
        <a href="{% url 'home:nurse'%}">
            View Nurses</a><br/>
    {% if user.username != patient.username and not user.username in doctorlist%}
        Only this patient can edit medical information<br/>
    {% endif %}

{% else %}
You must login or register to view this page<br/>
<button onclick="window.location. href='{% url 'home:register' %}'">
        Register New User Patient
</button><br/>
{% endif %}
<button onclick="window.location.href='/home/'">
    home
</button>
</body>
</html>